Hw04 auth
damanosalvag/nodejs-hw-rest-api pull request #3
Opened 2023-10-13 00:22 UTC by damanosalvag

Hola mentora, podrías por favor revisar mi código?
Pregunta: Si usamos jwt y no sesiones porque se creó una ruta logout?  Si el token solo se guarda en donde elija el front, ya que según leí, no se puede expirar un token sino hasta que se cumpla el tiempo que le fijamos, es decir, no es necesario hacer logout.  

Muchas gracias.

2023-10-13 08:31 UTC, alonakaliuzhna requested changes
hola 
no olvides que tienes que enviar la tarea por lms, recibo muchos correo y podria no ver tuyo, ademas es importante que la tarea queda entregada en lms 
sobre tu pregunta : si,aunque los tokens JWT son autónomos y suelen expirar en función de un tiempo predefinido, la creación de una ruta de logout puede ser útil para diversas razones relacionadas con la seguridad, el control de acceso y el cumplimiento de estándares de seguridad

2023-10-17 23:34 UTC, damanosalvag commented
Hola mentora, ya arregle la validación con el id del owner y creo que ya no debería faltar nada. Quedo pendiente, mil gracias.

2023-10-18 07:04 UTC, alonakaliuzhna commented
La propiedad "ref" en Mongoose se utiliza para establecer una relación entre dos esquemas. En este caso, estás estableciendo una relación entre los contactos y los usuarios mediante la propiedad "owner". Aunque puedas filtrar contactos utilizando el ID del propietario extraído del token, tener una relación definida facilita el manejo de datos, las consultas y la seguridad en tu aplicación. Es una buena práctica en aplicaciones que requieren control de acceso y relaciones entre entidades

2023-10-18 07:04 UTC, alonakaliuzhna approved these changes

2023-10-18 20:47 UTC, damanosalvag commented
Hola mentora, pregunta, aun me sale abierto el pull request, podria indicarme por favor como terminar de hacer el merge? muchas gracias.

2023-10-19 06:25 UTC, goit-latam commented
abajo  tienes que tener button merge

2023-10-19 06:27 UTC, Alonaklzh commented
abajo tiene que aparecer button merge

2023-10-19 18:37 UTC, merged